apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
    includeSelectors: false

images:
  - name: mlops-platform
    newName: 231629457413.dkr.ecr.us-west-2.amazonaws.com/mlops-dev-trainer
