apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mlflow-secrets-store
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: mlflow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-secrets
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mlflow-secrets-store
    kind: SecretStore
  target:
    name: mlflow-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        postgres-user: "{{ .username }}"
        postgres-password: "{{ .password }}"
        postgres-db: "{{ .database }}"
        backend_store_uri: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@mlflow-postgresql:5432/{{ .database | urlquery }}"
  data:
    - secretKey: username
      remoteRef:
        key: mlops/mlflow/database
        property: username
    - secretKey: password
      remoteRef:
        key: mlops/mlflow/database
        property: password
    - secretKey: database
      remoteRef:
        key: mlops/mlflow/database
        property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-minio-secrets
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mlflow-secrets-store
    kind: SecretStore
  target:
    name: mlflow-minio-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        root-user: "{{ .access_key }}"
        root-password: "{{ .secret_key }}"
        aws-access-key-id: "{{ .access_key }}"
        aws-secret-access-key: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: mlops/mlflow/s3
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: mlops/mlflow/s3
        property: secret_key
