import copy
import itertools
import re
from pathlib import Path

import yaml

GITOPS_ROOT = Path(__file__).resolve().parents[1]


def merge_template(base, override):
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge_template(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def render_value(value, parameters):
    if isinstance(value, str):
        return re.sub(r"{{\s*([A-Za-z0-9_]+)\s*}}", lambda m: str(parameters[m[1]]), value)
    if isinstance(value, dict):
        return {key: render_value(item, parameters) for key, item in value.items()}
    if isinstance(value, list):
        return [render_value(item, parameters) for item in value]
    return value


def generate_applications(gitops_root=GITOPS_ROOT):
    path = Path(gitops_root) / "applications/projects/mlops-applicationset.yaml"
    config = yaml.safe_load(path.read_text())
    if config.get("kind") != "ApplicationSet":
        raise ValueError(f"Expected ApplicationSet in {path}")
    applications = []
    for generator in config["spec"]["generators"]:
        matrix = generator["matrix"]
        lists = [item["list"]["elements"] for item in matrix["generators"]]
        template = merge_template(config["spec"]["template"], matrix.get("template", {}))
        for elements in itertools.product(*lists):
            parameters = {}
            for element in elements:
                parameters.update(element)
            rendered = render_value(template, parameters)
            applications.append({"apiVersion": "argoproj.io/v1alpha1", "kind": "Application", **rendered})
    return applications


def load_application(app, environment, gitops_root=GITOPS_ROOT):
    name = f"{app}-{environment}"
    for application in generate_applications(gitops_root):
        if application["metadata"]["name"] == name:
            return application
    raise ValueError(f"Application {name} is not generated by ApplicationSet")
