apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: inferenceservice.serving.kserve.io
  labels:
    app.kubernetes.io/name: kserve
    app.kubernetes.io/component: webhook
rules:
- operations: ["CREATE", "UPDATE"]
  apiGroups: ["serving.kserve.io"]
  apiVersions: ["v1beta1"]
  resources: ["inferenceservices"]
clientConfig:
  service:
    name: kserve-webhook-server-service
    namespace: kserve-system
    path: "/mutate-serving-kserve-io-v1beta1-inferenceservice"
admissionReviewVersions: ["v1", "v1beta1"]
sideEffects: None
failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: inferenceservice.serving.kserve.io
  labels:
    app.kubernetes.io/name: kserve
    app.kubernetes.io/component: webhook
rules:
- operations: ["CREATE", "UPDATE"]
  apiGroups: ["serving.kserve.io"]
  apiVersions: ["v1beta1"]
  resources: ["inferenceservices"]
clientConfig:
  service:
    name: kserve-webhook-server-service
    namespace: kserve-system
    path: "/validate-serving-kserve-io-v1beta1-inferenceservice"
admissionReviewVersions: ["v1", "v1beta1"]
sideEffects: None
failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: trainedmodel.serving.kserve.io
  labels:
    app.kubernetes.io/name: kserve
    app.kubernetes.io/component: webhook
rules:
- operations: ["CREATE", "UPDATE"]
  apiGroups: ["serving.kserve.io"]
  apiVersions: ["v1alpha1"]
  resources: ["trainedmodels"]
clientConfig:
  service:
    name: kserve-webhook-server-service
    namespace: kserve-system
    path: "/mutate-serving-kserve-io-v1alpha1-trainedmodel"
admissionReviewVersions: ["v1", "v1beta1"]
sideEffects: None
failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: trainedmodel.serving.kserve.io
  labels:
    app.kubernetes.io/name: kserve
    app.kubernetes.io/component: webhook
rules:
- operations: ["CREATE", "UPDATE"]
  apiGroups: ["serving.kserve.io"]
  apiVersions: ["v1alpha1"]
  resources: ["trainedmodels"]
clientConfig:
  service:
    name: kserve-webhook-server-service
    namespace: kserve-system
    path: "/validate-serving-kserve-io-v1alpha1-trainedmodel"
admissionReviewVersions: ["v1", "v1beta1"]
sideEffects: None
failurePolicy: Fail