apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: platform-config
    envs:
      - aws.env

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    config.kubernetes.io/local-config: "true"
