apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets-operator.yaml
  - cluster-secret-store.yaml
  - external-secrets.yaml
  - irsa-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/component: secret-management
      app.kubernetes.io/part-of: mlops-platform
    includeSelectors: false
