apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: production-infrastructure
  namespace: flux-system

resources:
  - ../../../sources
  - ../../../flux-config
  - ../../../addons
  - ../../../networking

patches:
  - patch: |
      - op: replace
        path: /spec/interval
        value: 10m
    target:
      kind: GitRepository
  - patch: |
      - op: replace
        path: /spec/interval
        value: 10m
    target:
      kind: Kustomization
      namespace: flux-system
  - patch: |
      - op: replace
        path: /spec/postBuild/substitute/cluster_name
        value: mlops-production-cluster
    target:
      kind: Kustomization
      name: infrastructure-addons
  - patch: |
      - op: replace
        path: /spec/postBuild/substitute/region
        value: us-west-2
    target:
      kind: Kustomization
      name: infrastructure-addons
  - patch: |
      - op: replace
        path: /spec/postBuild/substitute/environment
        value: production
    target:
      kind: Kustomization
      name: infrastructure-addons

commonLabels:
  environment: production
