apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-s3
  namespace: argo-workflows
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: artifact-repository
type: Opaque
data:
  # These values should be base64 encoded AWS credentials
  # In production, use IRSA (IAM Roles for Service Accounts) instead
  # This is a placeholder - actual credentials should be managed securely
  accesskey: ""  # base64 encoded access key
  secretkey: ""  # base64 encoded secret key
---
# Service Account with IRSA annotation for S3 access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-s3
  namespace: argo-workflows
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/argo-workflows-s3-role
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: service-account