apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single source of truth is in gitops/applications/apps/argo-workflows/base/
resources:
  - ../../../gitops/applications/apps/argo-workflows/base
