apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mlflow-allow-internal
  namespace: mlflow
  labels:
    app.kubernetes.io/name: network-policy
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: mlops-platform
spec:
  podSelector:
    matchLabels:
      app: mlflow-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kubeflow
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kserve
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 5000
