apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Single source of truth is in gitops/applications/apps/gatekeeper/base/
resources:
  - ../../../gitops/applications/apps/gatekeeper/base
