apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: production
    includeSelectors: false

images:
  - name: mlops-platform
    newName: 231629457413.dkr.ecr.us-east-1.amazonaws.com/mlops-prod-trainer

patches:
  - target:
      kind: WorkflowTemplate
      name: model-deployment-template
    patch: |-
      - op: test
        path: /spec/arguments/parameters/4/name
        value: ecr-repository
      - op: replace
        path: /spec/arguments/parameters/4/value
        value: 231629457413.dkr.ecr.us-east-1.amazonaws.com/mlops-prod-inference
  - target:
      kind: WorkflowTemplate
      name: ml-pipeline-template
    patch: |-
      - op: test
        path: /spec/arguments/parameters/5/name
        value: ecr-repository
      - op: replace
        path: /spec/arguments/parameters/5/value
        value: 231629457413.dkr.ecr.us-east-1.amazonaws.com/mlops-prod-inference
