apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mlflow-network-policy
  namespace: mlflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from Argo Workflows namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: argo-workflows
    ports:
    - protocol: TCP
      port: 5000
  # Allow ingress from monitoring namespace for metrics scraping
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 5000
  # Allow ingress from models namespace for model serving
  - from:
    - namespaceSelector:
        matchLabels:
          name: models
    ports:
    - protocol: TCP
      port: 5000
  # Allow internal communication within mlflow namespace
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 5000
    - protocol: TCP
      port: 5432
  egress:
  # Allow egress to PostgreSQL
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  # Allow egress to AWS services (S3, etc.)
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 80   # HTTP
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53