apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - peer-authentications.yaml
  - destination-rules.yaml
  - authorization-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/name: istio
      app.kubernetes.io/component: service-mesh
      app.kubernetes.io/part-of: mlops-platform
    includeSelectors: false
