apiVersion: v1
kind: Service
metadata:
  name: litmus-chaos-exporter
  namespace: litmus
  labels:
    app.kubernetes.io/name: litmus-chaos-exporter
    app.kubernetes.io/component: metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: litmus
    app.kubernetes.io/component: chaos-exporter
