apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/component: helm-repository
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  type: default
