apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../gitops/applications/apps/mlflow/overlays/dev

images:
  - name: 231629457413.dkr.ecr.us-east-1.amazonaws.com/mlops-dev-mlflow-server
    newName: mlflow-server

patches:
  - target:
      group: external-secrets.io
    patch: |-
      $patch: delete
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: removed-in-kind
  - target:
      group: monitoring.coreos.com
    patch: |-
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: removed-in-kind
